name: Deploy to Azure Container App (ACR)

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: fhirwebapi
  ACR_NAME: fhirregistry
  RESOURCE_GROUP: FHIRAppRG
  CONTAINERAPP_NAME: fhirwebapi
  CONTAINERAPP_ENV_NAME: fhir-env
  LOCATION: eastus

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure ACR Login
      run: az acr login --name ${{ env.ACR_NAME }}
    
    - name: Build and Push Docker Image to ACR
      run: |
        ACR_LOGIN_SERVER=$(az acr show --name $ACR_NAME --query loginServer --output tsv)
        docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:latest -f FHIRWebApi.Api/Dockerfile FHIRWebApi.Api
        docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest

    - name: Deploy to Azure Container App
      run: |
        ACR_LOGIN_SERVER=$(az acr show --name $ACR_NAME --query loginServer --output tsv)
        az containerapp update \
          --name $CONTAINERAPP_NAME \
          --resource-group $RESOURCE_GROUP \
          --image $ACR_LOGIN_SERVER/$IMAGE_NAME:latest \
          --environment $CONTAINERAPP_ENV_NAME
